
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # List files for debugging
      - name: List files in workspace
   

      # Log into Azure
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Validate Bicep file
      - name: Validate Bicep file
        run: az deployment group validate --resource-group bicep --template-file ./main.bicep

      # Deploy Bicep file
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: bicep
          template: ./main.bicep
          parameters: |
            storagePrefix=stg
          failOnStdErr: false
